services:
  backend:
    build: ./backend
    container_name: Mission5-Phase1-Backend
    ports:
      - 4000:4000
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    container_name: Mission5-Phase1-Frontend
    environment:
      NODE_ENV: production
    ports:
      - 5173:5173