services:
  Backend:
    build: ./Backend
    container_name: Mission5-Phase1-Backend
    ports:
      - 4000:4000
    env_file:
      - ./Backend/.env
    volumes:
      - ./Backend:/app
      - /app/node_modules
  Frontend:
    build:
      context: ./Frontend
      dockerfile: ./dockerfile
    container_name: Mission5-Phase1-Frontend
    enviroment:
      NODE_ENV: production
    ports:
      - 5173:5173